# Generated by Django 2.1.3 on 2018-12-01 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bitdimo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpostcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Bitdimo.AdminPost'),
        ),
        migrations.AlterField(
            model_name='adminpostimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Bitdimo.AdminPost'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area', to='Bitdimo.Area'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='Bitdimo.User'),
        ),
        migrations.AlterField(
            model_name='userpostcomment',
            name='time_comment',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='userpostimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Bitdimo.UserPost'),
        ),
    ]
